//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopStoreVG.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int IDHistory { get; set; }
        public int IDProductSale { get; set; }
    
        public virtual ProductSale ProductSale { get; set; }
    }
}
